ALTER SESSION SET CONTAINER = ORCLPDB1;

DECLARE
user_exist integer;
BEGIN
  SELECT count(*) INTO user_exist FROM dba_users WHERE username='PERF_TESTS';
  IF (user_exist = 0) THEN
    EXECUTE IMMEDIATE 'CREATE USER PERF_TESTS IDENTIFIED BY password';
   	EXECUTE IMMEDIATE 'GRANT CONNECT TO perf_tests CONTAINER=CURRENT';
  	EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO perf_tests CONTAINER=CURRENT';
 	EXECUTE IMMEDIATE 'GRANT RESOURCE TO perf_tests CONTAINER=CURRENT';
 	EXECUTE IMMEDIATE 'ALTER USER perf_tests QUOTA 2000M ON USERS';
  END IF;
END;
