OPTIONS (SKIP=1, ERRORS=100000, BINDSIZE=8000000, ROWS=5000 )

LOAD DATA
	infile '/dane/cities.csv' "str '\r\n'"
	INSERT
	INTO TABLE perf_tests.cities
	FIELDS TERMINATED BY ','
	(
	CITY_ID,
	COUNTRY,
	CITY,
	POSTAL_CODE
    )
